Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 
[('Queen', ' of ', 'joker'), ('Hearts', ' of ', 'joker'), ('King', ' of ', 'joker'), ('Spades', ' of ', 'joker'), ('10', ' of ', 'joker'), ('9', ' of ', 'joker'), ('8', ' of ', 'joker'), ('7', ' of ', 'joker'), ('6', ' of ', 'joker'), ('5', ' of ', 'joker'), ('4', ' of ', 'joker'), ('3', ' of ', 'joker'), ('2', ' of ', 'joker'), ('Queen', ' of ', 'jack'), ('Hearts', ' of ', 'jack'), ('King', ' of ', 'jack'), ('Spades', ' of ', 'jack'), ('10', ' of ', 'jack'), ('9', ' of ', 'jack'), ('8', ' of ', 'jack'), ('7', ' of ', 'jack'), ('6', ' of ', 'jack'), ('5', ' of ', 'jack'), ('4', ' of ', 'jack'), ('3', ' of ', 'jack'), ('2', ' of ', 'jack'), ('Queen', ' of ', 'clubs'), ('Hearts', ' of ', 'clubs'), ('King', ' of ', 'clubs'), ('Spades', ' of ', 'clubs'), ('10', ' of ', 'clubs'), ('9', ' of ', 'clubs'), ('8', ' of ', 'clubs'), ('7', ' of ', 'clubs'), ('6', ' of ', 'clubs'), ('5', ' of ', 'clubs'), ('4', ' of ', 'clubs'), ('3', ' of ', 'clubs'), ('2', ' of ', 'clubs'), ('Queen', ' of ', 'diamonds'), ('Hearts', ' of ', 'diamonds'), ('King', ' of ', 'diamonds'), ('Spades', ' of ', 'diamonds'), ('10', ' of ', 'diamonds'), ('9', ' of ', 'diamonds'), ('8', ' of ', 'diamonds'), ('7', ' of ', 'diamonds'), ('6', ' of ', 'diamonds'), ('5', ' of ', 'diamonds'), ('4', ' of ', 'diamonds'), ('3', ' of ', 'diamonds'), ('2', ' of ', 'diamonds')]
>>> ================================ RESTART ================================
>>> 
[('Queen', ' of ', 'joker'), ('Hearts', ' of ', 'joker'), ('King', ' of ', 'joker'), ('Spades', ' of ', 'joker'), ('10', ' of ', 'joker'), ('9', ' of ', 'joker'), ('8', ' of ', 'joker'), ('7', ' of ', 'joker'), ('6', ' of ', 'joker'), ('5', ' of ', 'joker'), ('4', ' of ', 'joker'), ('3', ' of ', 'joker'), ('2', ' of ', 'joker'), ('Queen', ' of ', 'jack'), ('Hearts', ' of ', 'jack'), ('King', ' of ', 'jack'), ('Spades', ' of ', 'jack'), ('10', ' of ', 'jack'), ('9', ' of ', 'jack'), ('8', ' of ', 'jack'), ('7', ' of ', 'jack'), ('6', ' of ', 'jack'), ('5', ' of ', 'jack'), ('4', ' of ', 'jack'), ('3', ' of ', 'jack'), ('2', ' of ', 'jack'), ('Queen', ' of ', 'clubs'), ('Hearts', ' of ', 'clubs'), ('King', ' of ', 'clubs'), ('Spades', ' of ', 'clubs'), ('10', ' of ', 'clubs'), ('9', ' of ', 'clubs'), ('8', ' of ', 'clubs'), ('7', ' of ', 'clubs'), ('6', ' of ', 'clubs'), ('5', ' of ', 'clubs'), ('4', ' of ', 'clubs'), ('3', ' of ', 'clubs'), ('2', ' of ', 'clubs'), ('Queen', ' of ', 'diamonds'), ('Hearts', ' of ', 'diamonds'), ('King', ' of ', 'diamonds'), ('Spades', ' of ', 'diamonds'), ('10', ' of ', 'diamonds'), ('9', ' of ', 'diamonds'), ('8', ' of ', 'diamonds'), ('7', ' of ', 'diamonds'), ('6', ' of ', 'diamonds'), ('5', ' of ', 'diamonds'), ('4', ' of ', 'diamonds'), ('3', ' of ', 'diamonds'), ('2', ' of ', 'diamonds')]
>>> ================================ RESTART ================================
>>> 
[('Queen', ' of ', 'joker'), ('Hearts', ' of ', 'joker'), ('King', ' of ', 'joker'), ('Spades', ' of ', 'joker'), ('10', ' of ', 'joker'), ('9', ' of ', 'joker'), ('8', ' of ', 'joker'), ('7', ' of ', 'joker'), ('6', ' of ', 'joker'), ('5', ' of ', 'joker'), ('4', ' of ', 'joker'), ('3', ' of ', 'joker'), ('2', ' of ', 'joker'), ('Queen', ' of ', 'jack'), ('Hearts', ' of ', 'jack'), ('King', ' of ', 'jack'), ('Spades', ' of ', 'jack'), ('10', ' of ', 'jack'), ('9', ' of ', 'jack'), ('8', ' of ', 'jack'), ('7', ' of ', 'jack'), ('6', ' of ', 'jack'), ('5', ' of ', 'jack'), ('4', ' of ', 'jack'), ('3', ' of ', 'jack'), ('2', ' of ', 'jack'), ('Queen', ' of ', 'clubs'), ('Hearts', ' of ', 'clubs'), ('King', ' of ', 'clubs'), ('Spades', ' of ', 'clubs'), ('10', ' of ', 'clubs'), ('9', ' of ', 'clubs'), ('8', ' of ', 'clubs'), ('7', ' of ', 'clubs'), ('6', ' of ', 'clubs'), ('5', ' of ', 'clubs'), ('4', ' of ', 'clubs'), ('3', ' of ', 'clubs'), ('2', ' of ', 'clubs'), ('Queen', ' of ', 'diamonds'), ('Hearts', ' of ', 'diamonds'), ('King', ' of ', 'diamonds'), ('Spades', ' of ', 'diamonds'), ('10', ' of ', 'diamonds'), ('9', ' of ', 'diamonds'), ('8', ' of ', 'diamonds'), ('7', ' of ', 'diamonds'), ('6', ' of ', 'diamonds'), ('5', ' of ', 'diamonds'), ('4', ' of ', 'diamonds'), ('3', ' of ', 'diamonds'), ('2', ' of ', 'diamonds')]

>>> ================================ RESTART ================================
>>> 
[('Queen', ' of ', 'joker'), ('Hearts', ' of ', 'joker'), ('King', ' of ', 'joker'), ('Spades', ' of ', 'joker'), ('10', ' of ', 'joker'), ('9', ' of ', 'joker'), ('8', ' of ', 'joker'), ('7', ' of ', 'joker'), ('6', ' of ', 'joker'), ('5', ' of ', 'joker'), ('4', ' of ', 'joker'), ('3', ' of ', 'joker'), ('2', ' of ', 'joker'), ('Queen', ' of ', 'jack'), ('Hearts', ' of ', 'jack'), ('King', ' of ', 'jack'), ('Spades', ' of ', 'jack'), ('10', ' of ', 'jack'), ('9', ' of ', 'jack'), ('8', ' of ', 'jack'), ('7', ' of ', 'jack'), ('6', ' of ', 'jack'), ('5', ' of ', 'jack'), ('4', ' of ', 'jack'), ('3', ' of ', 'jack'), ('2', ' of ', 'jack'), ('Queen', ' of ', 'clubs'), ('Hearts', ' of ', 'clubs'), ('King', ' of ', 'clubs'), ('Spades', ' of ', 'clubs'), ('10', ' of ', 'clubs'), ('9', ' of ', 'clubs'), ('8', ' of ', 'clubs'), ('7', ' of ', 'clubs'), ('6', ' of ', 'clubs'), ('5', ' of ', 'clubs'), ('4', ' of ', 'clubs'), ('3', ' of ', 'clubs'), ('2', ' of ', 'clubs'), ('Queen', ' of ', 'diamonds'), ('Hearts', ' of ', 'diamonds'), ('King', ' of ', 'diamonds'), ('Spades', ' of ', 'diamonds'), ('10', ' of ', 'diamonds'), ('9', ' of ', 'diamonds'), ('8', ' of ', 'diamonds'), ('7', ' of ', 'diamonds'), ('6', ' of ', 'diamonds'), ('5', ' of ', 'diamonds'), ('4', ' of ', 'diamonds'), ('3', ' of ', 'diamonds'), ('2', ' of ', 'diamonds')]
Traceback (most recent call last):
  File "E:/BlackJack Final.py", line 22, in <module>
    playerhand = cards [startedcard:startcard+3]
NameError: name 'startedcard' is not defined
>>> 
