Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 
[('Ace', ' of ', 'hearts'), ('King', ' of ', 'hearts'), ('Queen', ' of ', 'hearts'), ('Jack', ' of ', 'hearts'), ('10', ' of ', 'hearts'), ('9', ' of ', 'hearts'), ('8', ' of ', 'hearts'), ('7', ' of ', 'hearts'), ('6', ' of ', 'hearts'), ('5', ' of ', 'hearts'), ('4', ' of ', 'hearts'), ('3', ' of ', 'hearts'), ('2', ' of ', 'hearts'), ('Ace', ' of ', 'spades'), ('King', ' of ', 'spades'), ('Queen', ' of ', 'spades'), ('Jack', ' of ', 'spades'), ('10', ' of ', 'spades'), ('9', ' of ', 'spades'), ('8', ' of ', 'spades'), ('7', ' of ', 'spades'), ('6', ' of ', 'spades'), ('5', ' of ', 'spades'), ('4', ' of ', 'spades'), ('3', ' of ', 'spades'), ('2', ' of ', 'spades'), ('Ace', ' of ', 'diamonds'), ('King', ' of ', 'diamonds'), ('Queen', ' of ', 'diamonds'), ('Jack', ' of ', 'diamonds'), ('10', ' of ', 'diamonds'), ('9', ' of ', 'diamonds'), ('8', ' of ', 'diamonds'), ('7', ' of ', 'diamonds'), ('6', ' of ', 'diamonds'), ('5', ' of ', 'diamonds'), ('4', ' of ', 'diamonds'), ('3', ' of ', 'diamonds'), ('2', ' of ', 'diamonds'), ('Ace', ' of ', 'clubs'), ('King', ' of ', 'clubs'), ('Queen', ' of ', 'clubs'), ('Jack', ' of ', 'clubs'), ('10', ' of ', 'clubs'), ('9', ' of ', 'clubs'), ('8', ' of ', 'clubs'), ('7', ' of ', 'clubs'), ('6', ' of ', 'clubs'), ('5', ' of ', 'clubs'), ('4', ' of ', 'clubs'), ('3', ' of ', 'clubs'), ('2', ' of ', 'clubs')]
>>> ================================ RESTART ================================
>>> 
[('Ace', ' of ', 'hearts'), ('King', ' of ', 'hearts'), ('Queen', ' of ', 'hearts'), ('Jack', ' of ', 'hearts'), ('10', ' of ', 'hearts'), ('9', ' of ', 'hearts'), ('8', ' of ', 'hearts'), ('7', ' of ', 'hearts'), ('6', ' of ', 'hearts'), ('5', ' of ', 'hearts'), ('4', ' of ', 'hearts'), ('3', ' of ', 'hearts'), ('2', ' of ', 'hearts'), ('Ace', ' of ', 'spades'), ('King', ' of ', 'spades'), ('Queen', ' of ', 'spades'), ('Jack', ' of ', 'spades'), ('10', ' of ', 'spades'), ('9', ' of ', 'spades'), ('8', ' of ', 'spades'), ('7', ' of ', 'spades'), ('6', ' of ', 'spades'), ('5', ' of ', 'spades'), ('4', ' of ', 'spades'), ('3', ' of ', 'spades'), ('2', ' of ', 'spades'), ('Ace', ' of ', 'diamonds'), ('King', ' of ', 'diamonds'), ('Queen', ' of ', 'diamonds'), ('Jack', ' of ', 'diamonds'), ('10', ' of ', 'diamonds'), ('9', ' of ', 'diamonds'), ('8', ' of ', 'diamonds'), ('7', ' of ', 'diamonds'), ('6', ' of ', 'diamonds'), ('5', ' of ', 'diamonds'), ('4', ' of ', 'diamonds'), ('3', ' of ', 'diamonds'), ('2', ' of ', 'diamonds'), ('Ace', ' of ', 'clubs'), ('King', ' of ', 'clubs'), ('Queen', ' of ', 'clubs'), ('Jack', ' of ', 'clubs'), ('10', ' of ', 'clubs'), ('9', ' of ', 'clubs'), ('8', ' of ', 'clubs'), ('7', ' of ', 'clubs'), ('6', ' of ', 'clubs'), ('5', ' of ', 'clubs'), ('4', ' of ', 'clubs'), ('3', ' of ', 'clubs'), ('2', ' of ', 'clubs')]
>>> ================================ RESTART ================================
>>> 
[('Ace', ' of ', 'hearts'), ('King', ' of ', 'hearts'), ('Queen', ' of ', 'hearts'), ('Jack', ' of ', 'hearts'), ('10', ' of ', 'hearts'), ('9', ' of ', 'hearts'), ('8', ' of ', 'hearts'), ('7', ' of ', 'hearts'), ('6', ' of ', 'hearts'), ('5', ' of ', 'hearts'), ('4', ' of ', 'hearts'), ('3', ' of ', 'hearts'), ('2', ' of ', 'hearts'), ('Ace', ' of ', 'spades'), ('King', ' of ', 'spades'), ('Queen', ' of ', 'spades'), ('Jack', ' of ', 'spades'), ('10', ' of ', 'spades'), ('9', ' of ', 'spades'), ('8', ' of ', 'spades'), ('7', ' of ', 'spades'), ('6', ' of ', 'spades'), ('5', ' of ', 'spades'), ('4', ' of ', 'spades'), ('3', ' of ', 'spades'), ('2', ' of ', 'spades'), ('Ace', ' of ', 'diamonds'), ('King', ' of ', 'diamonds'), ('Queen', ' of ', 'diamonds'), ('Jack', ' of ', 'diamonds'), ('10', ' of ', 'diamonds'), ('9', ' of ', 'diamonds'), ('8', ' of ', 'diamonds'), ('7', ' of ', 'diamonds'), ('6', ' of ', 'diamonds'), ('5', ' of ', 'diamonds'), ('4', ' of ', 'diamonds'), ('3', ' of ', 'diamonds'), ('2', ' of ', 'diamonds'), ('Ace', ' of ', 'clubs'), ('King', ' of ', 'clubs'), ('Queen', ' of ', 'clubs'), ('Jack', ' of ', 'clubs'), ('10', ' of ', 'clubs'), ('9', ' of ', 'clubs'), ('8', ' of ', 'clubs'), ('7', ' of ', 'clubs'), ('6', ' of ', 'clubs'), ('5', ' of ', 'clubs'), ('4', ' of ', 'clubs'), ('3', ' of ', 'clubs'), ('2', ' of ', 'clubs')]
Traceback (most recent call last):
  File "C:/Users/astewar005/Desktop/Aleshia.py", line 16, in <module>
    playerhand = cards [startedcard: startcard+2]
NameError: name 'startedcard' is not defined
>>> ================================ RESTART ================================
>>> 
[('Ace', ' of ', 'hearts'), ('King', ' of ', 'hearts'), ('Queen', ' of ', 'hearts'), ('Jack', ' of ', 'hearts'), ('10', ' of ', 'hearts'), ('9', ' of ', 'hearts'), ('8', ' of ', 'hearts'), ('7', ' of ', 'hearts'), ('6', ' of ', 'hearts'), ('5', ' of ', 'hearts'), ('4', ' of ', 'hearts'), ('3', ' of ', 'hearts'), ('2', ' of ', 'hearts'), ('Ace', ' of ', 'spades'), ('King', ' of ', 'spades'), ('Queen', ' of ', 'spades'), ('Jack', ' of ', 'spades'), ('10', ' of ', 'spades'), ('9', ' of ', 'spades'), ('8', ' of ', 'spades'), ('7', ' of ', 'spades'), ('6', ' of ', 'spades'), ('5', ' of ', 'spades'), ('4', ' of ', 'spades'), ('3', ' of ', 'spades'), ('2', ' of ', 'spades'), ('Ace', ' of ', 'diamonds'), ('King', ' of ', 'diamonds'), ('Queen', ' of ', 'diamonds'), ('Jack', ' of ', 'diamonds'), ('10', ' of ', 'diamonds'), ('9', ' of ', 'diamonds'), ('8', ' of ', 'diamonds'), ('7', ' of ', 'diamonds'), ('6', ' of ', 'diamonds'), ('5', ' of ', 'diamonds'), ('4', ' of ', 'diamonds'), ('3', ' of ', 'diamonds'), ('2', ' of ', 'diamonds'), ('Ace', ' of ', 'clubs'), ('King', ' of ', 'clubs'), ('Queen', ' of ', 'clubs'), ('Jack', ' of ', 'clubs'), ('10', ' of ', 'clubs'), ('9', ' of ', 'clubs'), ('8', ' of ', 'clubs'), ('7', ' of ', 'clubs'), ('6', ' of ', 'clubs'), ('5', ' of ', 'clubs'), ('4', ' of ', 'clubs'), ('3', ' of ', 'clubs'), ('2', ' of ', 'clubs')]
Traceback (most recent call last):
  File "C:/Users/astewar005/Desktop/Aleshia.py", line 16, in <module>
    playerhand = cards [startedcard: startcard+2]
NameError: name 'startedcard' is not defined
>>> ================================ RESTART ================================
>>> 
[('Ace', ' of ', 'hearts'), ('King', ' of ', 'hearts'), ('Queen', ' of ', 'hearts'), ('Jack', ' of ', 'hearts'), ('10', ' of ', 'hearts'), ('9', ' of ', 'hearts'), ('8', ' of ', 'hearts'), ('7', ' of ', 'hearts'), ('6', ' of ', 'hearts'), ('5', ' of ', 'hearts'), ('4', ' of ', 'hearts'), ('3', ' of ', 'hearts'), ('2', ' of ', 'hearts'), ('Ace', ' of ', 'spades'), ('King', ' of ', 'spades'), ('Queen', ' of ', 'spades'), ('Jack', ' of ', 'spades'), ('10', ' of ', 'spades'), ('9', ' of ', 'spades'), ('8', ' of ', 'spades'), ('7', ' of ', 'spades'), ('6', ' of ', 'spades'), ('5', ' of ', 'spades'), ('4', ' of ', 'spades'), ('3', ' of ', 'spades'), ('2', ' of ', 'spades'), ('Ace', ' of ', 'diamonds'), ('King', ' of ', 'diamonds'), ('Queen', ' of ', 'diamonds'), ('Jack', ' of ', 'diamonds'), ('10', ' of ', 'diamonds'), ('9', ' of ', 'diamonds'), ('8', ' of ', 'diamonds'), ('7', ' of ', 'diamonds'), ('6', ' of ', 'diamonds'), ('5', ' of ', 'diamonds'), ('4', ' of ', 'diamonds'), ('3', ' of ', 'diamonds'), ('2', ' of ', 'diamonds'), ('Ace', ' of ', 'clubs'), ('King', ' of ', 'clubs'), ('Queen', ' of ', 'clubs'), ('Jack', ' of ', 'clubs'), ('10', ' of ', 'clubs'), ('9', ' of ', 'clubs'), ('8', ' of ', 'clubs'), ('7', ' of ', 'clubs'), ('6', ' of ', 'clubs'), ('5', ' of ', 'clubs'), ('4', ' of ', 'clubs'), ('3', ' of ', 'clubs'), ('2', ' of ', 'clubs')]
Traceback (most recent call last):
  File "C:/Users/astewar005/Desktop/Aleshia.py", line 16, in <module>
    playerhand = cards [startedcard: startcard+2]
NameError: name 'startedcard' is not defined
>>> 
